# Generated by Django 2.2.1 on 2019-07-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_reviewstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20)),
                ('reviewer_name', models.CharField(max_length=50)),
                ('reviewer_id', models.CharField(max_length=50)),
                ('review_date', models.CharField(max_length=10)),
                ('review_title', models.CharField(max_length=200)),
                ('review_helpful', models.CharField(max_length=20)),
                ('review_rating', models.CharField(max_length=20)),
                ('review_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20)),
                ('update_date', models.CharField(max_length=200)),
                ('insight_type', models.CharField(max_length=200)),
                ('insight_phrase', models.CharField(max_length=200)),
                ('insight_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='AmazonReviews',
        ),
        migrations.DeleteModel(
            name='ReviewStatus',
        ),
    ]
