# Generated by Django 2.2.1 on 2019-07-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_auto_20190709_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='AmazonProduct',
        ),
    ]
